name: Deploy to Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install vue cli
        run: yarn global add @vue/cli
        
      - name: Install yarn dependencies
        run: yarn install
        
      - name: Run build
        run: yarn run build

      - uses: crazy-max/ghaction-github-pages@v2.2.0
        if: github.ref == 'refs/heads/main'
        with:
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
